### ISSUE TITLE
Dependency for MST in FEve

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/fundiversity#2]
- [ade4](https://cran.r-project.org/package=ade4): `mstree()`
- [ape](https://cran.r-project.org/package=ape): `mst()`
- [igraph](https://cran.r-project.org/package=igraph): `mst()`
- [vegan](https://cran.r-project.org/package=vegan): `spantree()`

**Comment by Rekyt** [comment]
If we want to add FEve we should probably evaluate how often it is used in the literature and only focus on the most used indices in the literature?
Or the most independent dimensions (from Mouchet et al. 2010)
![image](https://user-images.githubusercontent.com/5593751/102243097-14b43580-3efb-11eb-894b-360ea6a48c1a.png)

**Comment by Rekyt** [comment]
Dependency-wise I think `igraph` and `vegan` have the smallest footprints.

`igraph::mst()` needs a graph object to be provided. So if it's the option we choose, we need to make a somewhat arbitrary choice to convert the input dissimilarity matrix into a graph to compute the Minimum Spanning Tree.
While `vegan::spantree()` requires directly a dissimilarity matrix.

That's why I think `vegan` should be the most appropriate choice.
