### ISSUE TITLE
New index: intersection between convex hulls

### ISSUE THREAD

**Issue by Rekyt** [Bisaloo/fundiversity#26]
As ecologists may be interested in the intersection of different convex hulls fundiversity could provide a wrapper around `geometry::intersectn()` that outputs the volume of the intersection between two volumes.

The input of this wrapper would be similar to `fd_fric()` (site-species matrix, trait matrix) and the output would be a distance matrix or rather a tidy data.frame with the first two columns giving the ids of the two considered sites, the third column would give the volume of the intersection.

Computationnally this could be quite intensive but should parallelize without issue (see #13).

**Comment by Rekyt** [comment]
The name could be `fd_fric_intersect()`, `fd_fric_join()`, `fd_chull_intersect()`, or `fd_chull_join()`?

The `hypervolume` 📦 proposes such functionality through the `hypervolume_join()` function.
To my knowledge no other package proposes this kind of function.

**Comment by Bisaloo** [comment]
I like `fd_fric_intersect()`

It makes clear it's related to `fd_fric()` and it's more mathematically accurate: it's indeed an intersection and not a join(?)

**Comment by Rekyt** [comment]
> It makes clear it's related to fd_fric() and it's more mathematically accurate: it's indeed an intersection and not a join(?)
Indeed!

One question that remains before actually implementing `fd_fric_intersect()`is the structure of the input.
It could simply be two sets of traits without any specification of a site-species matrix.
But some use cases may prefer computing several intersections of all sites?

**Comment by Bisaloo** [comment]
As mentioned, I think it makes sense to have the same inputs as `fd_fric()`.

The output would be a square matrix of size (number of sites) where the element ij is the intersection of the convex hull of the site i and the site j.

We *could* offer both this and the interface you are proposing but I'm afraid the accumulation of functions could become confusing.

If we end up going your road, we should absolutely document in the vignette how to efficiently compute this on all sites combinations. Otherwise, this leaves the door open for terribly suboptimal custom implementations.
